### ISSUE TITLE
Lab 5

### ISSUE THREAD

**Issue by mchu011** [oribix/rshell#1]
I have a midterm this week, so if we are meeting up before the ta's office hours on Friday or if I am adding anything to the code, then I can only be available Thursday and Tuesday afternoon to work on the lab code.

**Comment by oribix** [comment]
I have the same midterm and im stripped for time.

**Comment by mchu011** [comment]
Where are you now?

**Comment by oribix** [comment]
I went home. I am going to work from home. I am going to put up a copy of the file so that you can help me.

**Comment by mchu011** [comment]
okay
